// Code generated by ogen, DO NOT EDIT.
package ogen

type CreatePetsRes interface {
	createPetsRes()
}

type RedirectRes interface {
	redirectRes()
}

type ShowPetByIdRes interface {
	showPetByIdRes()
}
