// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"
	"net/url"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type CookieAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// CreatePetsCreated is response for CreatePets operation.
type CreatePetsCreated struct{}

func (*CreatePetsCreated) createPetsRes() {}

// DeleteSessionOK is response for DeleteSession operation.
type DeleteSessionOK struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *DeleteSessionOK) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *DeleteSessionOK) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) createPetsRes()  {}
func (*Error) redirectRes()    {}
func (*Error) showPetByIdRes() {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// GetSessionOK is response for GetSession operation.
type GetSessionOK struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *GetSessionOK) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *GetSessionOK) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Pet
type Pet struct {
	ID   int64     `json:"id"`
	Name string    `json:"name"`
	Tag  OptString `json:"tag"`
}

// GetID returns the value of ID.
func (s *Pet) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Pet) GetName() string {
	return s.Name
}

// GetTag returns the value of Tag.
func (s *Pet) GetTag() OptString {
	return s.Tag
}

// SetID sets the value of ID.
func (s *Pet) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Pet) SetName(val string) {
	s.Name = val
}

// SetTag sets the value of Tag.
func (s *Pet) SetTag(val OptString) {
	s.Tag = val
}

func (*Pet) showPetByIdRes() {}

type Pets []Pet

// PetsHeaders wraps Pets with response headers.
type PetsHeaders struct {
	XNext    OptString
	Response Pets
}

// GetXNext returns the value of XNext.
func (s *PetsHeaders) GetXNext() OptString {
	return s.XNext
}

// GetResponse returns the value of Response.
func (s *PetsHeaders) GetResponse() Pets {
	return s.Response
}

// SetXNext sets the value of XNext.
func (s *PetsHeaders) SetXNext(val OptString) {
	s.XNext = val
}

// SetResponse sets the value of Response.
func (s *PetsHeaders) SetResponse(val Pets) {
	s.Response = val
}

// RedirectFound is response for Redirect operation.
type RedirectFound struct {
	Location OptURI
}

// GetLocation returns the value of Location.
func (s *RedirectFound) GetLocation() OptURI {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *RedirectFound) SetLocation(val OptURI) {
	s.Location = val
}

func (*RedirectFound) redirectRes() {}
