services:
  oapi:
    container_name: ${APP_NAME}-oapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/oapi
    ports:
      - 1324:1324
    environment:
      ENV: local
      PORT: 1324
    volumes:
      - ../:/app
    restart: always
  ogen:
    container_name: ${APP_NAME}-ogen
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/ogen
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
    volumes:
      - ../:/app
    restart: always
